baseURL = "https://derrickabreo.github.io/derrickabreo/"
languageCode = "en-us"
title = "Derrick Abreo"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"
publishDir = "docs"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Derrick Abreo"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "derrickabreo"
  Email         = "derrickabreo@gmail.com"
  Twitter       = "derrickabreo"
  LinkedIn      = "derrick-abreo-aaa76012a"
  
  
  

## Main Menu
[[menu.main]]
  name = "artwork"
  weight = 100
  identifier = "artwork"
  url = "/artwork/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"

